In [ ]:
# Program - 3
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_d(x):
    return x * (1 - x)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        self.w_i_h = np.random.randn(input_size, hidden_size)
        self.b_h = np.random.randn(1, hidden_size)
        self.w_h_o = np.random.randn(hidden_size, output_size)
        self.b_o = np.random.randn(1, output_size)

    def forward(self, x):
        self.h_a = np.dot(x, self.w_i_h) + self.b_h
        self.h_o = sigmoid(self.h_a)

        self.o_a = np.dot(self.h_o, self.w_h_o) + self.b_o
        self.o_o = softmax(self.o_a)

        return self.o_o

    def backward(self, x, y, output, lr):
        m = y.shape[0]
        d_o = output - y
        e_h = d_o.dot(self.w_h_o.T)
        d_h = e_h * sigmoid_d(self.h_o)

        self.w_h_o -= self.h_o.T.dot(d_o) * lr / m
        self.b_o -= np.sum(d_o, axis=0, keepdims=True) * lr /m
        self.w_i_h -= x.T.dot(d_h) *lr / m
        self.b_h -= np.sum(d_h, axis=0, keepdims=True) * lr /m

    def loss_calculation(self, y_true, y_pred):
        y_pred = np.clip(y_pred, 1e-15, 1-1e-15)
        loss = -np.mean(np.sum(y_true * np.log(y_pred), axis=1))
        return loss


x = np.array([[0,0], [1,0], [0,1], [1,1]])
y = np.array([[1,0,0], [0,1,0], [0,1,0], [0,0,1]])

input_size, hidden_size, output_size = 2, 4, 3
lr = 0.1
epochs = 10000

nn = NeuralNetwork(input_size, hidden_size, output_size)

# train
for i in range(epochs):
    output = nn.forward(x)
    nn.backward(x, y, output, lr)

    if i % 1000 == 0:
        loss = nn.loss_calculation(y, output)
        print(f"Epoch {i} | Loss {loss:.4f}")

print("predicting outputs ")
prediction = nn.forward(x)
print(prediction)

print("\npredicting classes ")
print(np.argmax(prediction, axis=1))

# Program 3: Multi-Class Classification Using a Neural Network

This program implements a simple neural network to perform multi-class classification. It uses Python's `numpy` library for numerical computations and demonstrates forward propagation, backpropagation, loss calculation, and training of the network.

---

## **Features**

1. **Neural Network Architecture**:
   - Input Layer: 2 neurons (for input features).
   - Hidden Layer: 4 neurons.
   - Output Layer: 3 neurons (for multi-class output).

2. **Activation Functions**:
   - Sigmoid function for the hidden layer.
   - Softmax function for the output layer.

3. **Loss Function**:
   - Cross-entropy loss is used to evaluate the performance of the network.

4. **Training**:
   - The network is trained using backpropagation with a learning rate of 0.1 for 10,000 epochs.

5. **Prediction**:
   - After training, the network predicts the class probabilities and the corresponding class labels for the given inputs.

---

## **Code Overview**

### **Imports**
```python
import numpy as np
```
numpy: For numerical computations.

### Activation Functions
#### Sigmoid Function
```
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
```
Maps input values to the range (0, 1).

#### Sigmoid Derivative
```
def sigmoid_d(x):
    return x * (1 - x)
```
Derivative of the sigmoid function, used in backpropagation.

#### Softmax Function
```
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)
```
Converts input values into probabilities that sum to 1 for multi-class classification.
### Neural Network Class
```
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        self.w_i_h = np.random.randn(input_size, hidden_size)
        self.b_h = np.random.randn(1, hidden_size)
        self.w_h_o = np.random.randn(hidden_size, output_size)
        self.b_o = np.random.randn(1, output_size)

    def forward(self, x):
        self.h_a = np.dot(x, self.w_i_h) + self.b_h
        self.h_o = sigmoid(self.h_a)

        self.o_a = np.dot(self.h_o, self.w_h_o) + self.b_o
        self.o_o = softmax(self.o_a)

        return self.o_o

    def backward(self, x, y, output, lr):
        m = y.shape[0]
        d_o = output - y
        e_h = d_o.dot(self.w_h_o.T)
        d_h = e_h * sigmoid_d(self.h_o)

        self.w_h_o -= self.h_o.T.dot(d_o) * lr / m
        self.b_o -= np.sum(d_o, axis=0, keepdims=True) * lr / m
        self.w_i_h -= x.T.dot(d_h) * lr / m
        self.b_h -= np.sum(d_h, axis=0, keepdims=True) * lr / m

    def loss_calculation(self, y_true, y_pred):
        y_pred = np.clip(y_pred, 1e-15, 1 - 1e-15)
        loss = -np.mean(np.sum(y_true * np.log(y_pred), axis=1))
        return loss
```
#### Initialization:
Randomly initializes weights and biases for the input-to-hidden and hidden-to-output layers.
#### Forward Propagation:
Computes the activations for the hidden and output layers using the sigmoid and softmax functions.
#### Backward Propagation:
Updates weights and biases using the error gradient and learning rate.
#### Loss Calculation:
Computes the cross-entropy loss to evaluate the network's performance.
### Training and Prediction
```
x = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
y = np.array([[1, 0, 0], [0, 1, 0], [0, 1, 0], [0, 0, 1]])

input_size, hidden_size, output_size = 2, 4, 3
lr = 0.1
epochs = 10000

nn = NeuralNetwork(input_size, hidden_size, output_size)

# Train the network
for i in range(epochs):
    output = nn.forward(x)
    nn.backward(x, y, output, lr)

    if i % 1000 == 0:
        loss = nn.loss_calculation(y, output)
        print(f"Epoch {i} | Loss {loss:.4f}")

# Predict outputs
print("Predicting outputs:")
prediction = nn.forward(x)
print(prediction)

# Predict class labels
print("\nPredicting classes:")
print(np.argmax(prediction, axis=1))
```
#### Inputs and Outputs:
x: Input features.
y: One-hot encoded class labels.
#### Training:
The network is trained for 10,000 epochs with a learning rate of 0.1.
#### Prediction:
After training, the network predicts the class probabilities and the corresponding class labels.
### Output
#### Predicted Probabilities:

The network outputs probabilities for each class for the given inputs.
#### Predicted Class Labels:

The network predicts the class labels corresponding to the highest probabilities.
### How to Run
Ensure you have Python installed along with the required library:

Run the program in a Jupyter Notebook or any Python environment.

View the predicted probabilities and class labels for the given inputs.

### Example Output
```
Epoch 0 | Loss 1.2345
Epoch 1000 | Loss 0.4567
Epoch 2000 | Loss 0.2345
...
Epoch 9000 | Loss 0.1234

Predicting outputs:
[[0.98 0.01 0.01]
 [0.01 0.97 0.02]
 [0.01 0.97 0.02]
 [0.01 0.02 0.97]]

Predicting classes:
[0 1 1 2]
```
The outputs are probabilities for each class, and the predicted class labels are [0, 1, 1, 2].

## Conclusion
This program demonstrates how a simple neural network can be implemented to solve a multi-class classification problem. It showcases the use of forward propagation, backpropagation, loss calculation, and training to achieve the desired outputs.

